import { expect, test } from "@playwright/test";
import { login } from "./login";

test("version chip opens the player changelog", async ({ page }) => {
  await login(page);
  const chip = page.getByTestId("village-version");
  await expect(chip).toBeVisible();
  await expect(chip).toHaveAttribute("data-version", "1.11.1");
  await expect(chip).toContainText("v1.11.1");
  const onMap = await chip.evaluate((el) => Boolean(el.closest("[data-village-host], canvas")));
  expect(onMap).toBe(false);
  await expect(page).toHaveTitle("像素公司村 · 提示还在");
  const header = page.getByTestId("village-header");
  await expect(header.getByTestId("village-brand")).toHaveText("像素公司村");
  await expect(header.getByTestId("ship-title")).toHaveText("提示还在");

  await chip.click();
  const notes = page.getByTestId("release-notes");
  await expect(notes).toHaveJSProperty("open", true);
  await expect(notes).toBeVisible();
  await expect(notes).toContainText("更新日志");
  await expect(notes).toContainText("v1.11.1 · 提示还在");
  await expect(notes).toContainText("第一条提示会出来");
  await expect(notes).toContainText("v1.11.0 · 认得自己");
  await expect(notes).toContainText("不用先点「找我」");
  await expect(notes).toContainText("灶还温着");
  await expect(notes).toContainText("v1.10.0 · 窄屏先看清");
  await expect(notes).toContainText("分享卡片");
  await expect(notes).toContainText("双指捏合");
  await expect(notes).toContainText("相伴开着还是关着");
  await expect(notes).toContainText("暖点更清楚");
  await expect(notes).toContainText("v1.9.2 · 窗子还暖着");
  await expect(notes).toContainText("慢慢亮一亮");
  await expect(notes).toContainText("大小还是原来的");
  await expect(notes).toContainText("不挡点人");
  await expect(notes).toContainText("v1.9.1 · 挥手也亮一下");
  await expect(notes).toContainText("从人的卡片上挥手");
  await expect(notes).toContainText("v1.9.0 · 还想回村");
  await expect(notes).toContainText("脚下轻轻弹一下");
  await expect(notes).toContainText("天边的颜色不一样");
  await expect(notes).toContainText("两三颗暖点");
  await expect(notes).toContainText("分享村子");
  await expect(notes).toContainText("v1.8.0 · 还想多看一眼");
  await expect(notes).toContainText("小路边上多了草和花");
  await expect(notes).toContainText("屋顶多一条亮边");
  await expect(notes).toContainText("影子更软");
  await expect(notes).toContainText("暖木头");
  await expect(notes).toContainText("不是深蓝空地");
  await expect(notes).toContainText("眼睛先被路口拉过去");
  await expect(notes).toContainText("v1.7.0 · 还想点一下");
  await expect(notes).toContainText("又见面了");
  await expect(notes).toContainText("今日摸一下村里");
  await expect(notes).toContainText("路上慢点");
  await expect(notes).toContainText("v1.6.4 · 窄屏先看见田");
  await expect(notes).toContainText("下半截不再空着一块深蓝色");
  await expect(notes).toContainText("v1.6.3 · 告别廉价");
  await expect(notes).toContainText("不再像贴上去的纸片");
  await expect(notes).toContainText("眼睛先落在田上");
  await expect(notes).toContainText("v1.6.2 · 夜里认得出村子");
  await expect(notes).toContainText("田、屋子和人");
  await expect(notes).toContainText("蓝色方块");
  await expect(notes).toContainText("更新日志可以自己滑动");
  await expect(notes).toContainText("v1.6.1 · 回家在底栏");
  await expect(notes).toContainText("找我");
  await expect(notes).toContainText("旁边也有");
  await expect(notes).toContainText("v1.6.0 · 慢慢住下");
  await expect(notes).toContainText("隔天再来");
  await expect(notes).toContainText("v1.5.1 · 再来一趟");
  await expect(notes).toContainText("整颗按钮会亮一会儿");
  await expect(notes).toContainText("v1.5.0 · 再来一趟");
  await expect(notes).toContainText("v1.4.0 · 手机也想多待");
  await expect(notes).toContainText("还想回村");
  await expect(notes).toContainText("今日可做");
  await expect(notes).toContainText("再待一会儿");
  await expect(notes).toContainText("夜里还能认路");
  await expect(notes).toContainText("小路、水面");
  await expect(notes).toContainText("村里开张");
  await expect(notes).toContainText("分数环");
  await expect(notes).toContainText("不出现说过的话");
  await expect(notes).toContainText("玩乐雷达");
  await expect(notes).not.toContainText("原文");
  await expect(notes).not.toContainText("SITE_PASSWORD");
  await expect(notes).not.toContainText("INGEST_SECRET");
});
