import { expect, test } from "@playwright/test";
import { login } from "./login";

test("version chip opens the player changelog", async ({ page }) => {
  await login(page);
  const chip = page.getByTestId("village-version");
  await expect(chip).toBeVisible();
  await expect(chip).toHaveAttribute("data-version", "1.6.2");
  await expect(chip).toContainText("v1.6.2");
  const onMap = await chip.evaluate((el) => Boolean(el.closest("[data-village-host], canvas")));
  expect(onMap).toBe(false);
  await expect(page).toHaveTitle("像素公司村 · 夜里认得出村子");
  const header = page.getByTestId("village-header");
  await expect(header.getByTestId("village-brand")).toHaveText("像素公司村");
  await expect(header.getByTestId("ship-title")).toHaveText("回家在底栏");

  await chip.click();
  const notes = page.getByTestId("release-notes");
  await expect(notes).toHaveJSProperty("open", true);
  await expect(notes).toBeVisible();
  await expect(notes).toContainText("更新日志");
  await expect(notes).toContainText("v1.6.2 · 夜里认得出村子");
  await expect(notes).toContainText("田、屋子和人");
  await expect(notes).toContainText("蓝色方块");
  await expect(notes).toContainText("更新日志可以自己滑动");
  await expect(notes).toContainText("v1.6.1 · 回家在底栏");
  await expect(notes).toContainText("找我");
  await expect(notes).toContainText("旁边也有");
  await expect(notes).toContainText("v1.6.0 · 慢慢住下");
  await expect(notes).toContainText("隔天再来");
  await expect(notes).toContainText("v1.5.1 · 再来一趟");
  await expect(notes).toContainText("整颗按钮会亮一会儿");
  await expect(notes).toContainText("v1.5.0 · 再来一趟");
  await expect(notes).toContainText("v1.4.0 · 手机也想多待");
  await expect(notes).toContainText("还想回村");
  await expect(notes).toContainText("今日可做");
  await expect(notes).toContainText("再待一会儿");
  await expect(notes).toContainText("夜里还能认路");
  await expect(notes).toContainText("小路、水面");
  await expect(notes).toContainText("村里开张");
  await expect(notes).toContainText("分数环");
  await expect(notes).toContainText("不出现说过的话");
  await expect(notes).toContainText("玩乐雷达");
  await expect(notes).not.toContainText("原文");
  await expect(notes).not.toContainText("SITE_PASSWORD");
  await expect(notes).not.toContainText("INGEST_SECRET");
});
